# Generated by Django 2.2.1 on 2019-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitante', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField()),
            ],
        ),
    ]
